# Site Settings
title: My Resume
# url: 'http://webjeda.com'
# baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Taekang Woo
tagline: Researcher (computer vision)
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '[Engineering, Researching, Programming] <br />
Result-oriented Researcher with 1+ years of experience in corporate environment, 
have strong knowledge in Computer Vision, Machine Learning for Autonomous vehicle, Brain MRI, Face recognition. 
Highly motivated, confident professional with a good sense of humor.
<br> <br>

Have computer vision experience & code level solution<br>
Classfication (vgg ~ xception)<br>
Detection (ssd, yolo)<br>
Segmentation (unet, deeplab, pspnet)<br>
Feature extraction (HoG, FAST)<br>
Matching (stereo SGM, BM)<br>
3d reconstruction (disparity -> depth)<br>
Clustering (DBSCAN, meanshift, Kmeans)<br>
Tracking (median filter, KCF)
'

#sidebar links
email: wtk1101@gmail.com
# phone: 010 345 6789
website: tkwoo.github.io
linkedin: tkwooo
github: tkwoo
# twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-115046187-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
